version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: erp_api
    container_name: erp_api_container
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: erp_api_container
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: erp_v2
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
